### PR TITLE
Uwhscores comms

### LINKED ISSUE #30: Connect to uwhscores.com
Tracking Issue:

- [ ] Pull data from uwhscores
- [ ] Push scores to uwhscores
- [ ] Use game attributes when enabled

### LINKED ISSUE #34: Need to wait for score confirmation
The tournament manager doesn't wait for confirmation of score at the potential end of a game. It should ask for score confirmation at the end of any period that could be the end of the game.

### PR DESCRIPTION
**Pull request by TristanDebrunner**
Add communications to uwhscores:

- The app will always start in not uwhscores mode, but can be changed on the settings page
- There is a new confirm score page that appears anytime the game would end
- upon score confirmation, tries to upload scores to uwhscores if in uwhscores mode

Fixes #30
Fixes #34

### CODE REVIEW

**Comment by TristanDebrunner** [comment]
bors try

**Comment by TristanDebrunner** [comment]
New build:
[uwh-refbox.exe.zip](https://github.com/AtlatntisSports/uwh-refbox-rs/files/8942588/uwh-refbox.exe.zip)

**Comment by e-straily** [comment]
Change "Pool" to "Court" on uwh scores page

**Comment by TristanDebrunner** [comment]
Updated:
[uwh-refbox.exe.zip](https://github.com/AtlatntisSports/uwh-refbox-rs/files/8943750/uwh-refbox.exe.zip)

**Comment by e-straily** [comment]
bors+

**Pull request merged**
